{{- if .Values.prometheus.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shihao.fullname" . }}
  labels:
    {{- include "shihao.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "shihao.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}