import js from '@eslint/js';
import security from 'eslint-plugin-security';

export default [
  js.configs.recommended,
  {
    plugins: {
      security
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // 浏览器全局变量
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        HTMLCanvasElement: 'readonly',
        WebGLRenderingContext: 'readonly',
        WebGL2RenderingContext: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        AudioContext: 'readonly',

        // Node.js全局变量
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        setImmediate: 'readonly',
        global: 'readonly',

        // 其他全局变量
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        fetch: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        FormData: 'readonly',
        XMLHttpRequest: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        // 项目自定义全局变量
        EventBus: 'readonly',
        StateManager: 'readonly',
        PersonalitySystem: 'readonly'
      }
    },
    rules: {
      'indent': ['error', 2],
      'linebreak-style': 'off',
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-console': 'off',
      'no-debugger': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-throw-literal': 'error',
      'no-constant-condition': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'valid-typeof': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-trailing-spaces': 'error',
      'comma-dangle': ['error', 'never'],
      'arrow-parens': ['error', 'always'],
      'no-multiple-empty-lines': ['error', { 'max': 2 }],
      'prefer-template': 'error',
      'template-curly-spacing': ['error', 'never'],
      // Security plugin — 精准规则，无噪音
      'security/detect-buffer-noassert': 'error',
      'security/detect-child-process': 'error',
      'security/detect-disable-mustache-escape': 'error',
      'security/detect-eval-with-expression': 'error',
      'security/detect-new-buffer': 'error',
      'security/detect-no-csrf-before-method-override': 'error',
      'security/detect-pseudoRandomBytes': 'error',
      'security/detect-possible-timing-attacks': 'error',
      'security/detect-unsafe-regex': 'error',
      // 以下规则噪音较高，设为 warn 且仅限 src/ 生产代码
      'security/detect-non-literal-fs-filename': 'off',
      'security/detect-non-literal-regexp': 'off',
      'security/detect-object-injection': 'off'
    }
  },
  {
    files: ['test/**/*.js', '**/*.test.js', '**/*.spec.js'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        jest: 'readonly',
        assert: 'readonly'
      }
    },
    rules: {
      'no-console': 'off',
      'security/detect-child-process': 'off',
      'arrow-parens': 'off',
      'curly': 'off',
      'no-trailing-spaces': 'off',
      'comma-dangle': 'off',
      'prefer-template': 'off',
      'no-new-func': 'off',
      'indent': 'off'
    }
  },
  {
    files: ['server/**/*.js'],
    rules: {
      'no-console': 'off'
    }
  },
  {
    files: ['frontend/script.js'],
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^(allMemory|memoryTotalPages|isTyping|performanceOptimizer|currentIdentity|_.*)$', caughtErrors: 'none' }]
    }
  },
  {
    files: ['frontend/**/*.js'],
    languageOptions: {
      globals: {
        THREE: 'readonly',
        Audio: 'readonly',
        Image: 'readonly',
        speechSynthesis: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        WebSocket: 'readonly',
        RTCPeerConnection: 'readonly',
        RTCSessionDescription: 'readonly',
        RTCIceCandidate: 'readonly',
        MediaRecorder: 'readonly',
        Worker: 'readonly',
        self: 'readonly',
        NodeFilter: 'readonly',
        MutationObserver: 'readonly',
        Node: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLImageElement: 'readonly',
        MessageEvent: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        indexedDB: 'readonly',
        atob: 'readonly',
        io: 'readonly',
        Tesseract: 'readonly',
        BlendShapeExpressionSystem: 'readonly',
        ExpressionOverrideSystem: 'readonly',
        GLTFLoader: 'readonly',
        VRMLoaderPlugin: 'readonly',
        IdleAnimationController: 'readonly',
        OML2D: 'readonly',
        tf: 'readonly',
        caches: 'readonly',
        escapeHtml: 'readonly',
        filterMemory: 'readonly',
        closeCreateModal: 'readonly',
        append: 'readonly',
        openCreateModal: 'readonly',
        exportMemory: 'readonly',
        clearMemory: 'readonly',
        createPersonality: 'readonly',
        MultiModalVision: 'readonly',
        PerformanceOptimizer: 'readonly',
        TaskResultViewer: 'readonly',
        VirtualCharacter: 'readonly',
        Live2DComponent: 'readonly',
        VRMComponent: 'readonly',
        VoiceAvatar: 'readonly',
        TTSSystem: 'readonly',
        loadMemoryPage: 'readonly',
        deleteMemory: 'readonly',
        transformers: 'readonly',
        duckdb: 'readonly'
      }
    }
  },
  {
    ignores: [
      'node_modules/',
      'dist/',
      'build/',
      '*.min.js',
      'coverage/',
      '*.ts',
      '*.cjs',
      'shihao-web/',
      'shihao-video/',
      'EvoAgentX/',
      'scripts/',
      'tools/',
      'skills/',
      'skills-source/',
      'k6/',
      'plugins/',
      'examples/',
      'tests/performance/',
      '.opencode/',
      'test/archive/',
      'test-agents.js',
      'track-missing.js',
      'ultimate-check.js',
      'upgrade-to-v22.js',
      'final-v22-upgrade.js',
      'find-persistence.js',
      'full-diagnostics.js',
      'phase-c-verify.js',
      'quality-audit.js',
      'rebuild-agents.js',
      'rebuild-exact.js',
      'run_full_check.js',
      'run_opencode_check.js',
      '_run_integration.js',
      '_run_skipped_tests.js',
      '_run_skipped_v2.js',
      'analyze-v1-v9.js',
      'bot-discord.js',
      'brain-bridge.js',
      'brain-context.js',
      'brain-decision.js',
      'brain-entry.js',
      'check_path_security.js',
      'cleanup-duplicate-agents.js',
      'check-io.js',
      'cross-ref.js',
      'final-gap.js',
      'deep-scan.js',
      'D*.js'
    ]
  }
];