/**
 * LongTermMemoryRAG - 长期记忆RAG系统
 * 
 * 功能:
 * - 持久化存储(跨重启)
 * - 向量相似度搜索
 * - 自动记忆生成
 * - 手动添加记忆
 * - 记忆衰减和重要性加权
 * - 与DuckDB WASM集成
 */

class LongTermMemoryRAG {
  constructor(options = {}) {
    this.options = {
      // 存储目录
      storageDir: options.storageDir || 'long_term_memory',
      // 向量维度
      embeddingDim: options.embeddingDim || 384,
      // 最大记忆数
      maxMemories: options.maxMemories || 10000,
      // 自动保存间隔(ms)
      autoSaveInterval: options.autoSaveInterval || 30000,
      // 记忆衰减率
      decayRate: options.decayRate || 0.99,
      // 嵌入模型
      embeddingModel: options.embeddingModel || 'all-MiniLM-L6-v2',
      // 回调
      onReady: options.onReady || null,
      onMemoryAdded: options.onMemoryAdded || null,
      onError: options.onError || null,
      ...options
    };

    // 存储
    this.memories = [];
    this.embeddings = new Map();
    
    // 索引
    this.typeIndex = new Map();
    this.tagIndex = new Map();
    
    // 嵌入模型
    this.embeddingPipeline = null;
    
    // 统计
    this.stats = {
      totalMemories: 0,
      searchesPerformed: 0,
      autoGenerated: 0,
      lastSaved: null
    };

    // 自动保存定时器
    this.autoSaveTimer = null;
  }

  /**
   * 初始化
   */
  async init() {
    try {
      // 加载嵌入模型
      await this._loadEmbeddingModel();
      
      // 从本地存储加载记忆
      await this._loadFromStorage();
      
      // 启动自动保存
      this._startAutoSave();
      
      if (this.options.onReady) {
        this.options.onReady(this);
      }
      
      console.log(`[LongTermMemory] Initialized with ${this.memories.length} memories`);
      
    } catch (error) {
      console.error('[LongTermMemory] Init error:', error);
      if (this.options.onError) this.options.onError(error);
    }
  }

  /**
   * 加载嵌入模型
   */
  async _loadEmbeddingModel() {
    try {
      // 尝试使用Transformers.js
      const { pipeline } = await import('@huggingface/transformers');
      this.embeddingPipeline = await pipeline(
        'feature-extraction',
        this.options.embeddingModel,
        { quantized: true }
      );
      console.log('[LongTermMemory] Embedding model loaded');
    } catch (error) {
      console.warn('[LongTermMemory] Using local embeddings fallback');
      this.embeddingPipeline = null;
    }
  }

  /**
   * 获取文本嵌入
   */
  async getEmbedding(text) {
    if (this.embeddingPipeline) {
      try {
        const result = await this.embeddingPipeline(text, { pooling: 'mean', normalize: true });
        return Array.from(result.data);
      } catch (error) {
        console.warn('[LongTermMemory] Embedding error:', error);
      }
    }
    
    // 降级: 使用简单哈希嵌入
    return this._simpleEmbedding(text);
  }

  /**
   * 简单嵌入(降级方案)
   */
  _simpleEmbedding(text) {
    const words = text.toLowerCase().split(/\s+/);
    const vector = new Array(this.options.embeddingDim).fill(0);
    
    for (let i = 0; i < words.length; i++) {
      const hash = this._hashCode(words[i]);
      const idx = Math.abs(hash) % this.options.embeddingDim;
      vector[idx] += 1;
    }
    
    // 归一化
    const norm = Math.sqrt(vector.reduce((sum, v) => sum + v * v, 0));
    if (norm > 0) {
      for (let i = 0; i < vector.length; i++) {
        vector[i] /= norm;
      }
    }
    
    return vector;
  }

  /**
   * 哈希函数
   */
  _hashCode(str) {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash;
    }
    return hash;
  }

  /**
   * 添加记忆
   */
  async add(content, options = {}) {
    const memory = {
      id: this._generateId(),
      content,
      type: options.type || 'general',
      importance: options.importance || 0.5,
      tags: options.tags || [],
      metadata: options.metadata || {},
      createdAt: Date.now(),
      updatedAt: Date.now(),
      accessCount: 0,
      lastAccessedAt: Date.now()
    };

    // 生成嵌入
    const embedding = await this.getEmbedding(content);
    memory.embedding = embedding;

    // 添加到存储
    this.memories.push(memory);
    this.embeddings.set(memory.id, embedding);

    // 更新索引
    this._updateIndex(memory);

    // 限制数量
    if (this.memories.length > this.options.maxMemories) {
      this._pruneMemories();
    }

    this.stats.totalMemories++;

    if (this.options.onMemoryAdded) {
      this.options.onMemoryAdded(memory);
    }

    return memory;
  }

  /**
   * 添加对话记忆(自动生成)
   */
  async addConversation(role, content, metadata = {}) {
    // 只记录重要内容
    if (content.length < 10) return null;

    const importance = this._calculateImportance(content);
    
    return await this.add(content, {
      type: 'conversation',
      importance,
      tags: [role, 'auto-generated'],
      metadata: {
        ...metadata,
        role,
        autoGenerated: true
      }
    });
  }

  /**
   * 搜索记忆(语义搜索)
   */
  async search(query, options = {}) {
    const {
      limit = 5,
      type = null,
      minImportance = 0,
      timeRange = null
    } = options;

    const queryEmbedding = await this.getEmbedding(query);
    
    // 计算相似度
    let results = this.memories.map(memory => ({
      ...memory,
      similarity: this._cosineSimilarity(queryEmbedding, memory.embedding)
    }));

    // 过滤
    if (type) {
      results = results.filter(m => m.type === type);
    }
    
    if (minImportance > 0) {
      results = results.filter(m => m.importance >= minImportance);
    }
    
    if (timeRange) {
      const now = Date.now();
      results = results.filter(m => 
        now - m.createdAt <= timeRange
      );
    }

    // 排序
    results.sort((a, b) => {
      // 综合评分: 相似度 * 重要性 * 访问频率
      const scoreA = a.similarity * a.importance * (1 + a.accessCount * 0.01);
      const scoreB = b.similarity * b.importance * (1 + b.accessCount * 0.01);
      return scoreB - scoreA;
    });

    // 更新访问统计
    results.slice(0, limit).forEach(memory => {
      memory.accessCount = (memory.accessCount || 0) + 1;
      memory.lastAccessedAt = Date.now();
    });

    this.stats.searchesPerformed++;
    
    return results.slice(0, limit);
  }

  /**
   * 获取上下文
   */
  async getContext(topic, options = {}) {
    const results = await this.search(topic, { ...options, limit: options.limit || 5 });
    
    return results.map(memory => ({
      content: memory.content,
      type: memory.type,
      relevance: memory.similarity,
      timestamp: memory.createdAt
    }));
  }

  /**
   * 获取特定类型的记忆
   */
  async getByType(type, limit = 20) {
    const memories = this.typeIndex.get(type) || [];
    return memories
      .sort((a, b) => b.importance - a.importance)
      .slice(0, limit);
  }

  /**
   * 获取特定标签的记忆
   */
  async getByTag(tag, limit = 20) {
    const memories = this.tagIndex.get(tag) || [];
    return memories.slice(-limit);
  }

  /**
   * 更新记忆
   */
  async update(id, updates) {
    const index = this.memories.findIndex(m => m.id === id);
    if (index === -1) return null;

    const memory = this.memories[index];
    
    // 如果内容更新,重新生成嵌入
    if (updates.content && updates.content !== memory.content) {
      updates.embedding = await this.getEmbedding(updates.content);
      this.embeddings.set(id, updates.embedding);
    }

    // 更新
    Object.assign(memory, updates, { updatedAt: Date.now() });
    
    // 更新索引
    this._updateIndex(memory);
    
    return memory;
  }

  /**
   * 删除记忆
   */
  delete(id) {
    const index = this.memories.findIndex(m => m.id === id);
    if (index === -1) return false;

    this.memories.splice(index, 1);
    this.embeddings.delete(id);
    
    // 清理索引
    for (const [type, memories] of this.typeIndex) {
      const idx = memories.findIndex(m => m.id === id);
      if (idx !== -1) memories.splice(idx, 1);
    }
    
    for (const [tag, memories] of this.tagIndex) {
      const idx = memories.findIndex(m => m.id === id);
      if (idx !== -1) memories.splice(idx, 1);
    }

    this.stats.totalMemories--;
    return true;
  }

  /**
   * 计算重要性
   */
  _calculateImportance(text) {
    let importance = 0.5;
    
    // 长度因素
    if (text.length > 100) importance += 0.1;
    if (text.length > 500) importance += 0.1;
    
    // 关键词因素
    const importantKeywords = ['重要', '关键', '记住', '喜欢', '讨厌', 'important', 'remember'];
    for (const keyword of importantKeywords) {
      if (text.includes(keyword)) {
        importance += 0.1;
        break;
      }
    }
    
    // 情感因素
    const emotionalKeywords = ['爱', '恨', '喜欢', '讨厌', 'love', 'hate', 'amazing'];
    for (const keyword of emotionalKeywords) {
      if (text.includes(keyword)) {
        importance += 0.1;
        break;
      }
    }

    return Math.min(1, importance);
  }

  /**
   * 余弦相似度
   */
  _cosineSimilarity(a, b) {
    if (!a || !b || a.length !== b.length) return 0;
    
    let dotProduct = 0;
    let normA = 0;
    let normB = 0;
    
    for (let i = 0; i < a.length; i++) {
      dotProduct += a[i] * b[i];
      normA += a[i] * a[i];
      normB += b[i] * b[i];
    }
    
    return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB) || 1);
  }

  /**
   * 更新索引
   */
  _updateIndex(memory) {
    // 类型索引
    if (!this.typeIndex.has(memory.type)) {
      this.typeIndex.set(memory.type, []);
    }
    const typeList = this.typeIndex.get(memory.type);
    if (!typeList.find(m => m.id === memory.id)) {
      typeList.push(memory);
    }

    // 标签索引
    for (const tag of memory.tags) {
      if (!this.tagIndex.has(tag)) {
        this.tagIndex.set(tag, []);
      }
      const tagList = this.tagIndex.get(tag);
      if (!tagList.find(m => m.id === memory.id)) {
        tagList.push(memory);
      }
    }
  }

  /**
   * 清理低重要性记忆
   */
  _pruneMemories() {
    // 计算记忆价值分数
    const scored = this.memories.map(memory => {
      const age = Date.now() - memory.createdAt;
      const decay = Math.pow(this.options.decayRate, age / (24 * 60 * 60 * 1000));
      const score = memory.importance * decay * (1 + memory.accessCount * 0.1);
      return { memory, score };
    });

    // 按分数排序,删除最低分的
    scored.sort((a, b) => a.score - b.score);
    
    const toRemove = Math.floor(this.memories.length * 0.1);
    for (let i = 0; i < toRemove; i++) {
      this.delete(scored[i].memory.id);
    }

    console.log(`[LongTermMemory] Pruned ${toRemove} memories`);
  }

  /**
   * 启动自动保存
   */
  _startAutoSave() {
    if (this.options.autoSaveInterval > 0) {
      this.autoSaveTimer = setInterval(() => {
        this.saveToStorage();
      }, this.options.autoSaveInterval);
    }
  }

  /**
   * 保存到本地存储
   */
  async saveToStorage() {
    try {
      // 使用localStorage
      const data = {
        memories: this.memories.map(m => ({
          ...m,
          embedding: undefined // 不保存嵌入向量
        })),
        stats: this.stats,
        version: 1,
        savedAt: Date.now()
      };

      localStorage.setItem(
        this.options.storageDir,
        JSON.stringify(data)
      );

      this.stats.lastSaved = Date.now();
      console.log(`[LongTermMemory] Saved ${this.memories.length} memories`);

    } catch (error) {
      console.error('[LongTermMemory] Save error:', error);
    }
  }

  /**
   * 从本地存储加载
   */
  async _loadFromStorage() {
    try {
      const stored = localStorage.getItem(this.options.storageDir);
      if (!stored) return;

      const data = JSON.parse(stored);
      
      if (data.memories) {
        this.memories = data.memories;
        
        // 重新生成索引
        this.typeIndex.clear();
        this.tagIndex.clear();
        for (const memory of this.memories) {
          this._updateIndex(memory);
        }
      }

      if (data.stats) {
        Object.assign(this.stats, data.stats);
      }

      console.log(`[LongTermMemory] Loaded ${this.memories.length} memories`);

    } catch (error) {
      console.error('[LongTermMemory] Load error:', error);
    }
  }

  /**
   * 导出记忆
   */
  exportMemories() {
    return JSON.stringify({
      memories: this.memories,
      stats: this.stats,
      exportedAt: Date.now()
    }, null, 2);
  }

  /**
   * 导入记忆
   */
  async importMemories(json) {
    try {
      const data = JSON.parse(json);
      
      if (data.memories) {
        for (const memory of data.memories) {
          // 重新生成嵌入
          memory.embedding = await this.getEmbedding(memory.content);
          this.memories.push(memory);
          this.embeddings.set(memory.id, memory.embedding);
          this._updateIndex(memory);
        }
      }

      this.stats.totalMemories = this.memories.length;
      console.log(`[LongTermMemory] Imported ${data.memories.length} memories`);
      
    } catch (error) {
      console.error('[LongTermMemory] Import error:', error);
    }
  }

  /**
   * 生成ID
   */
  _generateId() {
    return `mem_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  /**
   * 获取统计
   */
  getStats() {
    return {
      ...this.stats,
      typeDistribution: Object.fromEntries(
        Array.from(this.typeIndex.entries()).map(([k, v]) => [k, v.length])
      )
    };
  }

  /**
   * 销毁
   */
  destroy() {
    if (this.autoSaveTimer) {
      clearInterval(this.autoSaveTimer);
    }
    this.saveToStorage();
  }
}

if (typeof window !== 'undefined') {
  window.LongTermMemoryRAG = LongTermMemoryRAG;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = LongTermMemoryRAG;
}
