"""Report generation module with Document IR pattern."""

from .document_ir import (
    DocumentIR,
    DocumentBuilder,
    Manifest,
    Chapter,
    BlockType,
    ListType,
    ChartType,
    Block,
    InlineText,
    HeadingBlock,
    ParagraphBlock,
    ListBlock,
    ListItemBlock,
    ChartBlock,
    TableBlock,
    ImageBlock,
    CodeBlock,
    QuoteBlock,
    DividerBlock,
    WarningBlock,
    InfoBlock,
    TableOfContents,
    ThemeTokens,
)
from .html_renderer import HTMLRenderer, render_document

__all__ = [
    "DocumentIR",
    "DocumentBuilder",
    "Manifest",
    "Chapter",
    "BlockType",
    "ListType",
    "ChartType",
    "Block",
    "InlineText",
    "HeadingBlock",
    "ParagraphBlock",
    "ListBlock",
    "ListItemBlock",
    "ChartBlock",
    "TableBlock",
    "ImageBlock",
    "CodeBlock",
    "QuoteBlock",
    "DividerBlock",
    "WarningBlock",
    "InfoBlock",
    "TableOfContents",
    "ThemeTokens",
    "HTMLRenderer",
    "render_document",
]
