"""
TradingAgents-CN Agent State Models
Multi-Agent LLM Stock Analysis System

定义智能体系统中的各种状态模型，包括：
- AgentState: 主要状态模型
- InvestDebateState: 投资辩论状态
- RiskDebateState: 风险辩论状态
"""

from typing import Annotated, Optional, List, Dict, Any, TypedDict
from datetime import datetime


class BaseState(TypedDict):
    """基础状态模型"""
    id: str
    created_at: str
    updated_at: str
    status: str  # initialized, running, completed, failed


class AnalystReport(TypedDict, total=False):
    """分析师报告"""
    expert_id: str
    expert_name: str
    expert_role: str
    content: str
    timestamp: str
    confidence: float
    metadata: Dict[str, Any]


class MarketReport(AnalystReport):
    """市场分析师报告"""
    pass


class FundamentalsReport(AnalystReport):
    """基本面分析师报告"""
    pass


class NewsReport(AnalystReport):
    """新闻分析师报告"""
    pass


class SentimentReport(AnalystReport):
    """情绪分析师报告"""
    pass


class DebatePosition(TypedDict):
    """辩论立场"""
    debater_id: str
    debater_name: str
    stance: str  # bullish, bearish, neutral
    arguments: List[str]
    confidence: float
    timestamp: str


class JudgeDecision(TypedDict):
    """裁判决策"""
    judge_id: str
    judge_name: str
    decision: str  # proceed, caution, abort
    reasoning: str
    confidence: float
    timestamp: str


class InvestDebateState(TypedDict):
    """
    投资辩论状态
    管理看涨方和看跌方的辩论过程
    """
    bull_history: Annotated[str, "Bullish Conversation history"]
    bear_history: Annotated[str, "Bearish Conversation history"]
    history: Annotated[str, "Conversation history"]
    current_bull_response: Annotated[str, "Latest bull response"]
    current_bear_response: Annotated[str, "Latest bear response"]
    judge_decision: Annotated[str, "Final judge decision"]
    count: Annotated[int, "Conversation length"]
    bull_confidence: float
    bear_confidence: float


class RiskDebateState(TypedDict):
    """
    风险辩论状态
    管理激进、保守、中性三方的风险评估辩论
    """
    risky_history: Annotated[str, "Risky Agent's Conversation history"]
    safe_history: Annotated[str, "Safe Agent's Conversation history"]
    neutral_history: Annotated[str, "Neutral Agent's Conversation history"]
    history: Annotated[str, "Conversation history"]
    latest_speaker: Annotated[str, "Agent that spoke last"]
    current_risky_response: Annotated[str, "Latest risky response"]
    current_safe_response: Annotated[str, "Latest safe response"]
    current_neutral_response: Annotated[str, "Latest neutral response"]
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Conversation length"]


class ToolCallState(TypedDict):
    """工具调用状态"""
    market_tool_call_count: Annotated[int, "Market analyst tool call counter"]
    news_tool_call_count: Annotated[int, "News analyst tool call counter"]
    sentiment_tool_call_count: Annotated[int, "Social media analyst tool call counter"]
    fundamentals_tool_call_count: Annotated[int, "Fundamentals analyst tool call counter"]


class AgentState(BaseState):
    """
    主要的智能体状态模型
    包含所有分析师报告、辩论状态和最终决策
    """
    # 基础信息
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    sender: Annotated[str, "Agent that sent this message"]

    # 分析师报告
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Analyst"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst"]

    # 工具调用计数
    market_tool_call_count: Annotated[int, "Market analyst tool call counter"]
    news_tool_call_count: Annotated[int, "News analyst tool call counter"]
    sentiment_tool_call_count: Annotated[int, "Social media analyst tool call counter"]
    fundamentals_tool_call_count: Annotated[int, "Fundamentals analyst tool call counter"]

    # 投资辩论状态
    investment_debate_state: Annotated[InvestDebateState, "Current state of the debate on if to invest or not"]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    # 交易员计划
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # 风险辩论状态
    risk_debate_state: Annotated[RiskDebateState, "Current state of the debate on evaluating risk"]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # 额外信息
    messages: Annotated[List[Dict[str, Any]], "Message history"]
    errors: Annotated[List[Dict[str, Any]], "Error records"]


class TaskState(BaseState):
    """
    任务状态模型
    用于跟踪异步任务的执行状态
    """
    task_id: str
    ticker: str
    trade_date: str
    progress: float  # 0.0 - 1.0
    current_phase: str  # analysis, debate, risk, decision
    current_node: Optional[str]
    result: Optional[Dict[str, Any]]
    error: Optional[str]
    started_at: str
    completed_at: Optional[str]


def create_initial_state(
    company_name: str,
    trade_date: str,
    task_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    创建初始状态

    Args:
        company_name: 公司名称或股票代码
        trade_date: 交易日期
        task_id: 任务ID

    Returns:
        初始状态字典
    """
    import uuid

    now = datetime.now().isoformat()
    initial_task_id = task_id or str(uuid.uuid4())

    return {
        # 基础信息
        "id": initial_task_id,
        "created_at": now,
        "updated_at": now,
        "status": "initialized",

        # 目标信息
        "company_of_interest": company_name,
        "trade_date": trade_date,
        "sender": "system",

        # 分析师报告（初始为空）
        "market_report": "",
        "sentiment_report": "",
        "news_report": "",
        "fundamentals_report": "",

        # 工具调用计数
        "market_tool_call_count": 0,
        "news_tool_call_count": 0,
        "sentiment_tool_call_count": 0,
        "fundamentals_tool_call_count": 0,

        # 投资辩论状态
        "investment_debate_state": {
            "bull_history": "",
            "bear_history": "",
            "history": "",
            "current_bull_response": "",
            "current_bear_response": "",
            "judge_decision": "",
            "count": 0,
            "bull_confidence": 0.0,
            "bear_confidence": 0.0,
        },
        "investment_plan": "",

        # 交易员计划
        "trader_investment_plan": "",

        # 风险辩论状态
        "risk_debate_state": {
            "risky_history": "",
            "safe_history": "",
            "neutral_history": "",
            "history": "",
            "latest_speaker": "",
            "current_risky_response": "",
            "current_safe_response": "",
            "current_neutral_response": "",
            "judge_decision": "",
            "count": 0,
        },
        "final_trade_decision": "",

        # 消息和错误
        "messages": [],
        "errors": [],
    }


def update_state_timestamp(state: Dict[str, Any]) -> Dict[str, Any]:
    """更新状态时间戳"""
    state["updated_at"] = datetime.now().isoformat()
    return state


def add_message(
    state: Dict[str, Any],
    role: str,
    content: str,
    metadata: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """添加消息到状态"""
    message = {
        "role": role,
        "content": content,
        "timestamp": datetime.now().isoformat(),
        "metadata": metadata or {},
    }
    state["messages"].append(message)
    return update_state_timestamp(state)


def add_error(
    state: Dict[str, Any],
    error: Exception,
    context: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """添加错误到状态"""
    error_record = {
        "error": str(error),
        "type": type(error).__name__,
        "context": context or {},
        "timestamp": datetime.now().isoformat(),
    }
    state["errors"].append(error_record)
    return update_state_timestamp(state)
